#!/bin/sh
if [ "$1" = "configure" ]; then

    echo "Adding MIME information for Buddi files..."
    update-mime-database /usr/share/mime
    update-desktop-database -v /usr/share/applications

	chmod 755 /usr/bin/buddi
fi
