#!/bin/bash
# Creates javadocs
#
############################

DEST=/Users/Wyatt/Desktop
JAVADOCS=javadocs
WWW=/srv/www/devel.buddi.thecave.homeunix.org
javadoc -d ${DEST}/${JAVADOCS} -sourcepath src:../Moss/src -subpackages org

tar -C ${DEST} -czvf ${DEST}/${JAVADOCS}.tgz ${JAVADOCS}

scp ${DEST}/${JAVADOCS}.tgz www-data@flare:${WWW}
ssh www-data@flare tar -C ${WWW} -zxvf ${WWW}/${JAVADOCS}.tgz
ssh www-data@flare rm ${WWW}/${JAVADOCS}.tgz
