#!/bin/bash
#
# Jar the plugins which are listed in the PLUGINS variable.  You should enter
# the plugins in the variable in the following format:
#
#    Name,path/relative/to/plugin_src
#
# Each plugin entry should be separated by whitespace.
#
# If you include translation (.lang) files, put them in the root 
# directory of your plugin.
#
#########################

PLUGINS='ExportQIF,org/homeunix/thecave/plugins/export/qif'

TEMP=temp
mkdir $TEMP

for X in ${PLUGINS}; do
	PLUGIN_NAME=`echo ${X} | cut -d, -f1`
	X=`echo ${X} | cut -d, -f2`	
	mkdir -p ${TEMP}/${X}
	cp -R bin/${X}/* ${TEMP}/${X}
	cp -R plugin_src/${X}/* ${TEMP}/${X}
	mv ${TEMP}/${X}/*.lang $TEMP
	cd $TEMP
	jar -cvf ${PLUGIN_NAME}.jar *
	mv ${PLUGIN_NAME}.jar ../Plugins
	cd ..
	rm -rf ${TEMP}
done
