#!/bin/sh
# Buddi launch script.
#
# Run this to launch Buddi.  You can put this in your path (/usr/local/bin, 
# or wherever you desire) and it will work fine.
#
# If you don't have Java in your path (or if the Java in your path is GNU
# Java, which will not work with Buddi), you can set the JAVA variable below.
#
#############################################################

####
# Start User Configuration
####

# Find the default java binary
JAVA=`which java`

# If you wish to override the default, uncomment and enter the path here.
#JAVA='/usr/bin/java'

# The working directory.  This is used to store custom languages, and (if 
# the data file is within this directory) will be used as a relative path in
# the preferences file.  If you plan on editing languages, you will need
# to have write access to this directory.
WORKING_DIR="${HOME}/.buddi"

# The location of the Buddi.jar file.
JAR_DIR="/usr/bin"

####
# End User Configuration
####



####
# Check configuration settings
####

# Check if Java is installed.
if [ ! -x ${JAVA} ]; then
	echo "I cannot find your Java executable.  Please set the JAVA variable in this script."
	exit 1
fi

# Check that we have the Sun Java version.
${JAVA} -version 2>&1 | grep -q 'Java(TM)'
if [ ${?} != 0 ]; then
	echo "The installed Java version does not appear to be a Sun JVM.  Please set the JAVA variable in this script to the correct location of the Sun JVM."
	exit 1
fi

# Is Buddi.jar installed
if [ ! -r ${JAR_DIR}/Buddi.jar ]; then
        echo "I cannot find the Buddi.jar file in ${JAR_DIR}.  Please move Buddi.jar to this location, or modify the JAR_DIR variable in this script."
        exit 1
fi 

# TODO: Check for writable working directory.


####
# Launch Buddi
####

${JAVA} -Duser.dir=${WORKING_DIR} -jar ${JAR_DIR}/Buddi.jar --slackware $*
