#!/bin/sh
if [ "$1" = install ]; then
    for X in buddi Buddi.jar; do
        dpkg-divert --package buddi --rename --add /usr/bin/$X
    done

    dpkg-divert --package buddi --rename --add /usr/share/applications/buddi.desktop

    for X in 16 22 24 32 36 48 64 72 96 128 192; do 
        dpkg-divert --package buddi --rename --add /usr/share/icons/hicolor/${X}x${X}/apps/buddi.png
    done
    dpkg-divert --package buddi --rename --add /usr/share/pixmaps/buddi.png
    
    dpkg-divert --package buddi --rename --add /usr/share/doc/buddi/README
fi
