/*
 * Created on Jul 30, 2007 by wyatt
 */
package org.homeunix.thecave.buddi.model;

import java.util.Date;

import org.homeunix.thecave.buddi.plugin.api.exception.InvalidValueException;

public interface Account extends Source{
	
	/**
	 * Get the account type
	 * @return
	 */
	public AccountType getAccountType();
	/**
	 * Returns the current balance.  This is a volatile value, and is 
	 * generated by calling updateBalance().
	 * @return
	 */
	public long getBalance();	
	/**
	 * Returns the balance as of the given date.
	 * @param d
	 * @return
	 */
	public long getBalance(Date d);
	/**
	 * Returns the starting date of this account.  This is defined as the earliest
	 * date referenced by one of the associated transactions.  This is a volatile
	 * value, and is generated on the fly when calling this methd.
	 * @return
	 */
	public Date getStartDate();
	/**
	 * Returns the starting balance associated with this account.
	 * @return
	 */
	public long getStartingBalance();
	/**
	 * Sets the account type
	 * @param accountType
	 * @throws InvalidValueException
	 */
	public void setAccountType(AccountType accountType) throws InvalidValueException;
	/**
	 * Sets the starting balance
	 * @param startingBalance
	 * @throws InvalidValueException
	 */
	public void setStartingBalance(long startingBalance) throws InvalidValueException;
	/**
	 * Updates the balance for this account, by navigating all associated transactions.
	 * Calling this will also update the balanceTo or balanceFrom fields in 
	 * each transaction, representing the balance at the time of that transaction.
	 */
	public void updateBalance();
}
